"""
54_p2_local_analysis.py - 2-adic Local Analysis for Perfect Cuboid Selmer Group

KEY QUESTION: Does the local condition at p=2 enlarge Sel^2 beyond delta(J[2])?

For A_r: y^2 = f(u) = u(u+1)(u+r^2)(2u+(r-1)^2)(2u+(r+1)^2)

The curve has BAD reduction at p=2 for ALL r >= 2:
  f(u) = 0 mod 2 for all u (all coefficients of f are even when expanded)

We analyze the 2-adic valuation structure of delta(D_{ij}) components
to determine whether the local image at p=2 is already captured by J[2].
"""

from fractions import Fraction
from itertools import combinations
from sympy import factorint
import numpy as np

def roots_of_f(r):
    return [Fraction(0), Fraction(-1), Fraction(-r**2),
            Fraction(-(r-1)**2, 2), Fraction(-(r+1)**2, 2)]

def f_prime_at(roots, idx, c=4):
    prod = Fraction(c)
    for k in range(5):
        if k != idx:
            prod *= (roots[idx] - roots[k])
    return prod

def delta_D(r, i, j):
    roots = roots_of_f(r)
    fp_i = f_prime_at(roots, i)
    fp_j = f_prime_at(roots, j)
    img = []
    for k in range(5):
        if k == i:
            img.append(fp_i / (roots[i] - roots[j]))
        elif k == j:
            img.append(fp_j / (roots[j] - roots[i]))
        else:
            img.append((roots[k] - roots[i]) * (roots[k] - roots[j]))
    return img

def v2(q):
    """2-adic valuation of a Fraction (mod 2 => only parity matters)."""
    if q == 0:
        return float('inf')
    n = abs(q.numerator)
    d = abs(q.denominator)
    vn = 0
    while n % 2 == 0:
        n //= 2
        vn += 1
    vd = 0
    while d % 2 == 0:
        d //= 2
        vd += 1
    return vn - vd

def v2_parity(q):
    """v_2(q) mod 2 -- this is what matters in Q*/Q*^2."""
    v = v2(q)
    if v == float('inf'):
        return 0
    return v % 2

def unit_part_mod8(q):
    """Extract the odd part of q, reduced mod 8."""
    if q == 0:
        return 0
    n = q.numerator
    d = q.denominator
    while n % 2 == 0:
        n //= 2
    while d % 2 == 0:
        d //= 2
    # Now n/d is odd/odd
    # Compute n * d^{-1} mod 8
    d_inv = pow(d, -1, 8) if d % 2 == 1 else 0
    return (n * d_inv) % 8

def analyze_2adic_delta(r):
    """Analyze 2-adic structure of all delta(D_{ij}) components."""
    results = []
    for i, j in combinations(range(5), 2):
        d = delta_D(r, i, j)
        v2_vals = [v2(x) for x in d]
        v2_parities = [v2_parity(x) for x in d]
        units_mod8 = [unit_part_mod8(x) for x in d]
        results.append({
            'pair': (i, j),
            'v2': v2_vals,
            'v2_par': v2_parities,
            'unit8': units_mod8,
            'values': d
        })
    return results

def print_2adic_table(r):
    """Print 2-adic analysis table for given r."""
    print(f"\nr = {r}:")
    print(f"  {'D(i,j)':8s} | {'v2(d0)':>6s} {'v2(d1)':>6s} {'v2(d2)':>6s} {'v2(d3)':>6s} {'v2(d4)':>6s} | {'u0%8':>4s} {'u1%8':>4s} {'u2%8':>4s} {'u3%8':>4s} {'u4%8':>4s}")
    print("  " + "-" * 80)
    results = analyze_2adic_delta(r)
    for res in results:
        i, j = res['pair']
        v = res['v2']
        u = res['unit8']
        print(f"  D({i},{j})   | {v[0]:6d} {v[1]:6d} {v[2]:6d} {v[3]:6d} {v[4]:6d} | {u[0]:4d} {u[1]:4d} {u[2]:4d} {u[3]:4d} {u[4]:4d}")

def compute_2adic_f2_image(r):
    """Compute the F_2 image of delta(J[2]) using 2-adic coordinates.

    In Q_2*/Q_2*^2, every element is represented by 3 bits:
      (-1)^a * 2^b * (unit class c)
    where:
      a in {0,1} (sign)
      b in {0,1} (2-adic valuation mod 2)
      c in {0,1} (unit = 1 or 5 mod 8 => c=0; unit = 3 or 7 mod 8 => c=1)

    So Q_2*/Q_2*^2 = (Z/2)^3, generated by {-1, 2, 5}.
    """
    images = []
    for i, j in combinations(range(5), 2):
        d = delta_D(r, i, j)
        vec = []
        for k in range(5):
            # Component k gives 3 F_2 coordinates
            val = d[k]
            sign_bit = 1 if val < 0 else 0
            v2_bit = v2_parity(val)
            u = unit_part_mod8(val if val > 0 else -val)
            # unit class: 1,7 -> 0; 3,5 -> 1 (quadratic residues mod 8)
            # Actually Q_2*/Q_2*^2 = {1, -1, 2, -2, 5, -5, 10, -10}
            # Generators: -1, 2, 5
            # 1 mod 8 -> (0,0), 3 mod 8 -> (1,1), 5 mod 8 -> (1,0), 7 mod 8 -> (0,1)
            # Wait, let me be more careful.
            # Q_2*/Q_2*^2 has order 8, generated by -1, 2, 5
            # u mod 8: 1->(0,0,0), 3->(1,0,1), 5->(0,0,1), 7->(1,0,0) for (-1,2,5) basis
            # Hmm, need to think about this more carefully.
            # Z_2* / Z_2*^2 = {1, 3, 5, 7} mod 8, order 4
            # Squares in Z_2*: 1 mod 8 only
            # So Z_2*/Z_2*^2 = (Z/2)^2 generated by {-1, 5} or {3, 5}
            # Wait: -1 = 7 mod 8. So -1 is NOT a square in Z_2.
            # Full: Q_2*/Q_2*^2 = <-1> x <2> x <5> = (Z/2)^3

            # Coordinates in basis (-1, 2, 5):
            # sign: 1 if negative
            # v2 mod 2
            # "5-part": determined by odd part mod 8
            # u=1: (0,0), u=3: (1,1), u=5: (0,1), u=7: (1,0) for (-1,5) in Z_2*/Z_2*^2
            # Because: 3 = -1*5*1^(-2)... let me just compute:
            # 1 = 1 -> (-1)^0 * 5^0
            # 3 mod 8: 3 is not 1,5,7=-1,35=-3 mod 8.
            # Actually 3 = (-1)*(-3) = (-1)*(5) mod 8? No, -3 = 5 mod 8. So 3 = (-1)*5 mod Q_2*^2?
            # Check: (-1)*5 = -5 = 3 mod 8. Yes! So 3 = (-1)*5 mod 8.
            # 7 = -1 mod 8. So 7 = (-1) mod Q_2*^2.
            # 5 = 5 mod 8.
            # Summary for odd part u mod 8:
            # u=1: (-1)^0 * 5^0 -> (0, 0)
            # u=3: (-1)^1 * 5^1 -> (1, 1)  [since -5 = 3 mod 8]
            # u=5: (-1)^0 * 5^1 -> (0, 1)
            # u=7: (-1)^1 * 5^0 -> (1, 0)  [since -1 = 7 mod 8]

            if u == 1:
                neg_bit, five_bit = 0, 0
            elif u == 3:
                neg_bit, five_bit = 1, 1
            elif u == 5:
                neg_bit, five_bit = 0, 1
            elif u == 7:
                neg_bit, five_bit = 1, 0
            else:
                neg_bit, five_bit = 0, 0  # shouldn't happen

            # Combine sign from value with sign from unit decomposition
            total_neg = (sign_bit + neg_bit) % 2

            vec.extend([total_neg, v2_bit, five_bit])

        images.append(vec)

    return images

def compute_local_rank_at_2(r):
    """Compute F_2-rank of delta(J[2]) image in (Q_2*/Q_2*^2)^5."""
    images = compute_2adic_f2_image(r)
    mat = np.array(images, dtype=int) % 2
    # Gaussian elimination
    n, m = mat.shape
    rank = 0
    for col in range(m):
        found = False
        for row in range(rank, n):
            if mat[row, col] == 1:
                mat[[rank, row]] = mat[[row, rank]]
                found = True
                break
        if not found:
            continue
        for row in range(n):
            if row != rank and mat[row, col] == 1:
                mat[row] = (mat[row] + mat[rank]) % 2
        rank += 1
    return rank

def main():
    print("=" * 70)
    print("2-ADIC LOCAL ANALYSIS FOR PERFECT CUBOID SELMER GROUP")
    print("=" * 70)

    # Part 1: Detailed 2-adic valuation tables
    print("\n--- Part 1: 2-adic valuations of delta components ---")
    for r in [2, 3, 4, 5, 7, 10]:
        print_2adic_table(r)

    # Part 2: Local rank at p=2
    print("\n" + "=" * 70)
    print("--- Part 2: F_2-rank of delta(J[2]) in (Q_2*/Q_2*^2)^5 ---")
    print("Q_2*/Q_2*^2 = (Z/2)^3, so (Q_2*/Q_2*^2)^5 = (Z/2)^15")
    print("J[2] = (Z/2)^4, so max possible rank = 4")
    print()

    all_rank_4 = True
    for r in range(2, 101):
        rank = compute_local_rank_at_2(r)
        if rank != 4:
            print(f"r = {r}: LOCAL rank at p=2 = {rank}  ***")
            all_rank_4 = False
        elif r <= 20 or r % 25 == 0:
            print(f"r = {r:3d}: LOCAL rank at p=2 = {rank}")

    if all_rank_4:
        print("\n*** ALL r=2..100: local rank at p=2 = 4 ***")
        print("=> delta(J[2]) injects into the LOCAL Kummer image at p=2")

    # Part 3: Compare global vs local dimensions
    print("\n" + "=" * 70)
    print("--- Part 3: Dimension comparison ---")
    print("dim(local image at p=2) vs dim(delta(J[2])) globally")
    print()

    # The KEY question: is the local image at p=2 EXACTLY delta(J[2])?
    # If local image has dim > 4, there could be extra Selmer classes.
    # We check by computing the full local Kummer image dimension.

    # For a genus-2 curve with bad reduction, the local Kummer image
    # J(Q_2)/2J(Q_2) injects into (Q_2*/Q_2*^2)^5 via the same delta map.
    # The question is whether this image is LARGER than delta(J[2]).

    # By the exact sequence:
    #   0 -> J[2](Q_2) -> J(Q_2)/2J(Q_2) -> H^1(Q_2, J[2])
    # and dim(J(Q_2)/2J(Q_2)) = dim(J[2](Q_2)) + 2*dim(J) = 4 + 4 = 8 (by Tate local duality)
    # Wait, for abelian varieties over Q_p:
    # dim_{F_2}(J(Q_p)/2J(Q_p)) = dim(J[2](Q_p)) + 2g (by local Tate duality, when all 2-torsion is rational)
    # For our case: J[2](Q) = (Z/2)^4 (all 2-torsion rational), g=2
    # So dim(J(Q_2)/2J(Q_2)) = 4 + 4 = 8

    print("By Tate local duality for abelian varieties over Q_2:")
    print("  dim_{F_2}(J(Q_2)/2J(Q_2)) = dim(J[2](Q_2)) + 2*g")
    print("  = 4 + 2*2 = 8")
    print()
    print("The delta map sends J(Q_2)/2J(Q_2) into (Q_2*/Q_2*^2)^5 = (Z/2)^15")
    print("with image of dimension 8.")
    print()
    print("delta(J[2]) has dimension 4 inside this 8-dimensional image.")
    print("The EXTRA 4 dimensions come from non-torsion local points.")
    print()
    print("For Sel^2, we need: for each class in (Q_S*/Q_S*^2)^5,")
    print("  it lies in Sel^2 iff it is locally in the image at EVERY prime p.")
    print()
    print("The question is: does the intersection of local conditions")
    print("cut down to exactly delta(J[2]) = dim 4?")

    # Part 4: Explicit local image structure at p=2
    print("\n" + "=" * 70)
    print("--- Part 4: Structure of v_2 patterns ---")
    print()

    # For each delta(D_{ij}), look at the v_2 pattern
    # This reveals the 2-adic structure
    for r in [2, 3, 5]:
        print(f"\nr = {r}:")
        for i, j in combinations(range(5), 2):
            d = delta_D(r, i, j)
            v2s = [v2(x) for x in d]
            # Also compute the squarefree part
            sfs = []
            for x in d:
                if x == 0:
                    sfs.append(0)
                else:
                    sf = 1
                    n = abs(x.numerator * x.denominator)
                    if n > 1:
                        for p, e in factorint(n).items():
                            if e % 2 == 1:
                                sf *= p
                    if x < 0:
                        sf = -sf
                    sfs.append(sf)
            print(f"  D({i},{j}): v2 = {v2s}, sqfree = {sfs}")

if __name__ == "__main__":
    main()
