"""
55_full_selmer.py - Full 2-Selmer Group Computation via Stoll's Method

For A_r: y^2 = f(u) = u(u+1)(u+r^2)(2u+(r-1)^2)(2u+(r+1)^2)
with L = Q^5 (fully split) and Cl(O_{L,S}) = 0.

Implements the FULL fake Selmer group computation:
1. Build Q(S,2)^5 as F_2-vector space
2. Impose norm condition (product = 1 mod Q*^2)
3. For each p in S, compute local projection and impose local image constraint
4. Count surviving dimension

The local image at odd p: delta(J[2](Q_p)) = 4-dimensional in (Q_p*/Q_p*^2)^5
The local image at p=2: delta(J[2](Q_2)) projected to (Q_2*/Q_2*^2)^5
"""

from fractions import Fraction
from itertools import combinations
from sympy import factorint, legendre_symbol
import numpy as np

def roots_of_f(r):
    return [Fraction(0), Fraction(-1), Fraction(-r**2),
            Fraction(-(r-1)**2, 2), Fraction(-(r+1)**2, 2)]

def f_prime_at(roots, idx, c=4):
    prod = Fraction(c)
    for k in range(5):
        if k != idx:
            prod *= (roots[idx] - roots[k])
    return prod

def delta_D(r, i, j):
    roots = roots_of_f(r)
    fp_i = f_prime_at(roots, i)
    fp_j = f_prime_at(roots, j)
    img = []
    for k in range(5):
        if k == i:
            img.append(fp_i / (roots[i] - roots[j]))
        elif k == j:
            img.append(fp_j / (roots[j] - roots[i]))
        else:
            img.append((roots[k] - roots[i]) * (roots[k] - roots[j]))
    return img

def bad_primes(r):
    S = {2}
    roots = roots_of_f(r)
    for i in range(5):
        for j in range(i+1, 5):
            d = roots[i] - roots[j]
            n = abs(d.numerator * d.denominator)
            if n > 1:
                for p in factorint(n):
                    S.add(p)
    return sorted(S)

def vp(q, p):
    """p-adic valuation of Fraction q."""
    if q == 0:
        return float('inf')
    n = abs(q.numerator)
    d = abs(q.denominator)
    v = 0
    while n % p == 0:
        n //= p
        v += 1
    while d % p == 0:
        d //= p
        v -= 1
    return v

def project_to_Qp_mod_sq(q, p, basis):
    """Project q in Q(S,2) to Q_p*/Q_p*^2.

    For odd p: Q_p*/Q_p*^2 = (Z/2)^2, generated by {p, nonsquare_unit}
    Returns [v_p mod 2, unit_class] where unit_class depends on Legendre symbols.

    For p=2: Q_2*/Q_2*^2 = (Z/2)^3, generated by {-1, 2, 5}
    Returns [sign_bit, v_2 mod 2, five_bit]
    """
    if p == 2:
        return _project_to_Q2(q, basis)
    else:
        return _project_to_Qp_odd(q, p, basis)

def _project_to_Qp_odd(q, p, basis):
    """For odd p: project to Q_p*/Q_p*^2 = F_2^2 = [v_p mod 2, unit class]."""
    # v_p(q) mod 2
    v = vp(q, p)
    val_bit = v % 2

    # Unit class: q/p^v mod p, is it a QR?
    # Remove the p-part
    n = q.numerator
    d = q.denominator
    # Make n, d coprime to p
    while n % p == 0:
        n //= p
    while d % p == 0:
        d //= p
    # Now n/d is a p-adic unit
    # Compute n * d^{-1} mod p
    unit = (n * pow(d, p-2, p)) % p
    if unit == 0:
        unit_bit = 0  # shouldn't happen
    else:
        leg = legendre_symbol(unit, p)
        unit_bit = 0 if leg == 1 else 1

    return [val_bit, unit_bit]

def _project_to_Q2(q, basis):
    """For p=2: project to Q_2*/Q_2*^2 = F_2^3 = [sign, v_2 mod 2, 5-class]."""
    if q == 0:
        return [0, 0, 0]

    sign_bit = 1 if q < 0 else 0

    # v_2
    v = vp(q, 2)
    v2_bit = v % 2

    # Unit part mod 8
    n = abs(q.numerator)
    d = abs(q.denominator)
    while n % 2 == 0:
        n //= 2
    while d % 2 == 0:
        d //= 2
    # n/d is odd/odd, compute mod 8
    d_inv = pow(d, -1, 8)
    u = (n * d_inv) % 8

    # Decompose u in Z_2*/Z_2*^2 = <-1, 5>
    # u=1: (0,0), u=3: (-1)*5 -> (1,1), u=5: (0,1), u=7: -1 -> (1,0)
    if u == 1:
        neg_from_unit, five_bit = 0, 0
    elif u == 3:
        neg_from_unit, five_bit = 1, 1
    elif u == 5:
        neg_from_unit, five_bit = 0, 1
    elif u == 7:
        neg_from_unit, five_bit = 1, 0
    else:
        neg_from_unit, five_bit = 0, 0

    total_sign = (sign_bit + neg_from_unit) % 2
    return [total_sign, v2_bit, five_bit]

def basis_projection_matrix_odd_p(p, basis):
    """Build the linear map from Q(S,2) basis to Q_p*/Q_p*^2 for odd p.

    basis = [-1, p_1, ..., p_k] (the S-unit basis)
    Each basis element b maps to a 2-bit vector in Q_p*/Q_p*^2.
    Returns a (2 x len(basis)) matrix over F_2.
    """
    mat = []
    for b in basis:
        if b == -1:
            # -1 has v_p = 0, Legendre(-1, p) = (-1)^{(p-1)/2}
            val_bit = 0
            leg = legendre_symbol(-1, p)
            unit_bit = 0 if leg == 1 else 1
        elif b == p:
            # p has v_p = 1, unit part = 1 (QR)
            val_bit = 1
            unit_bit = 0
        else:
            # prime q != p: v_p = 0, Legendre(q, p)
            val_bit = 0
            leg = legendre_symbol(b, p)
            unit_bit = 0 if leg == 1 else 1
        mat.append([val_bit, unit_bit])
    return np.array(mat, dtype=int).T  # shape (2, len(basis))

def basis_projection_matrix_p2(basis):
    """Build the linear map from Q(S,2) basis to Q_2*/Q_2*^2.

    Returns a (3 x len(basis)) matrix over F_2.
    Q_2*/Q_2*^2 = <-1, 2, 5> = F_2^3.
    """
    mat = []
    for b in basis:
        if b == -1:
            # -1 in Q_2*: unit = 7 mod 8 -> (-1)^1 * 5^0 * 2^0
            # Sign: 1, v_2: 0, five: 0
            vec = [1, 0, 0]
        elif b == 2:
            # 2 in Q_2*: 2 = 2^1 * 1
            vec = [0, 1, 0]
        else:
            # odd prime q: v_2 = 0, unit class depends on q mod 8
            q_mod8 = b % 8
            if q_mod8 == 1:
                vec = [0, 0, 0]  # square in Z_2*
            elif q_mod8 == 3:
                vec = [1, 0, 1]  # -5 = 3 mod 8
            elif q_mod8 == 5:
                vec = [0, 0, 1]  # 5 mod 8
            elif q_mod8 == 7:
                vec = [1, 0, 0]  # -1 = 7 mod 8
            else:
                vec = [0, 0, 0]
        mat.append(vec)
    return np.array(mat, dtype=int).T  # shape (3, len(basis))

def compute_fake_selmer(r, verbose=False):
    """Compute dim(Sel^2(J(A_r))) using the full Stoll 2-descent.

    Returns the dimension of the fake Selmer group F.
    Since Cl(O_{L,S}) = 0 for L = Q^5, we have Sel^2 = F.
    """
    S = bad_primes(r)
    basis = [-1] + list(S)  # basis for Q(S,2)
    dim_basis = len(basis)  # = |S| + 1

    if verbose:
        print(f"r = {r}: S = {S}, |S|+1 = {dim_basis}")

    # Step 1: Build Q(S,2)^5 as F_2^{5*dim_basis}
    total_dim = 5 * dim_basis

    # Step 2: Norm condition: for each basis element b,
    # sum of coordinates (comp_i, b) for i=0..4 must be 0
    # This gives dim_basis constraints
    norm_constraints = []
    for b_idx in range(dim_basis):
        row = [0] * total_dim
        for comp in range(5):
            row[comp * dim_basis + b_idx] = 1
        norm_constraints.append(row)

    # Step 3a: Condition at infinity (real place)
    # The projection to (R*/R*^2)^5 = (Z/2)^5 is the sign map.
    # The local Kummer image at infinity = delta(J(R)/2J(R)).
    # For odd p: J(Q_p)/2J(Q_p) = J[2], but at infinity, J(R)/2J(R)
    # includes only those 2-torsion elements that are in 2J(R).
    # We compute the SIGNS of delta(D_{ij}) as the real image of J[2].
    local_constraints = []

    sign_images = []
    for i, j in combinations(range(5), 2):
        d = delta_D(r, i, j)
        sign_vec = []
        for k in range(5):
            sign_vec.append(1 if d[k] < 0 else 0)
        sign_images.append(sign_vec)

    sign_mat = np.array(sign_images, dtype=int) % 2  # (10, 5)
    # Row reduce to find rank
    sm = sign_mat.copy()
    sn, sm_cols = sm.shape
    sign_pivots = []
    sc = 0
    for sr in range(sn):
        while sc < sm_cols:
            found = False
            for sr2 in range(sr, sn):
                if sm[sr2, sc] == 1:
                    sm[[sr, sr2]] = sm[[sr2, sr]]
                    found = True
                    break
            if found:
                sign_pivots.append(sc)
                for sr2 in range(sn):
                    if sr2 != sr and sm[sr2, sc] == 1:
                        sm[sr2] = (sm[sr2] + sm[sr]) % 2
                sc += 1
                break
            sc += 1

    sign_rank = len(sign_pivots)
    sign_ortho = sm_cols - sign_rank  # constraints from infinity

    if sign_ortho > 0:
        pivot_set = set(sign_pivots)
        free_cs = [c for c in range(sm_cols) if c not in pivot_set]
        for fc in free_cs:
            w = np.zeros(sm_cols, dtype=int)
            w[fc] = 1
            for ri, pc in enumerate(sign_pivots):
                if sm[ri, fc] == 1:
                    w[pc] = 1
            # w is in F_2^5 orthogonal to all sign images
            # The constraint on x in Q(S,2)^5: the sign of component i of x
            # is determined by the -1 coordinate of that component.
            # So the constraint is: sum_i w[i] * x[i * dim_basis + 0] = 0
            # (where index 0 in the basis is -1)
            constraint = [0] * total_dim
            for comp in range(5):
                constraint[comp * dim_basis + 0] = w[comp]  # -1 is basis[0]
            if any(c != 0 for c in constraint):
                local_constraints.append(constraint)

    if verbose:
        print(f"  infinity: sign_rank={sign_rank}, ortho_dim={sign_ortho}")

    # Step 3b: Local conditions at each prime p in S
    for p in S:
        if p == 2:
            proj_mat = basis_projection_matrix_p2(basis)  # (3, dim_basis)
            local_dim = 3  # dim Q_2*/Q_2*^2
        else:
            proj_mat = basis_projection_matrix_odd_p(p, basis)  # (2, dim_basis)
            local_dim = 2  # dim Q_p*/Q_p*^2

        # Build full projection: Q(S,2)^5 -> (Q_p*/Q_p*^2)^5
        # This is block-diagonal with 5 copies of proj_mat
        full_proj_rows = 5 * local_dim
        full_proj = np.zeros((full_proj_rows, total_dim), dtype=int)
        for comp in range(5):
            r1 = comp * local_dim
            r2 = r1 + local_dim
            c1 = comp * dim_basis
            c2 = c1 + dim_basis
            full_proj[r1:r2, c1:c2] = proj_mat

        # Compute the local Kummer image: delta(D_{ij}) projected to (Q_p*/Q_p*^2)^5
        local_images = []
        for i, j in combinations(range(5), 2):
            d = delta_D(r, i, j)
            vec = []
            for k in range(5):
                if p == 2:
                    vec.extend(_project_to_Q2(d[k], basis))
                else:
                    vec.extend(_project_to_Qp_odd(d[k], p, basis))
            local_images.append(vec)

        local_img_mat = np.array(local_images, dtype=int) % 2

        # Compute the orthogonal complement of the local image in (Q_p*/Q_p*^2)^5
        # Any element of the Selmer group, when projected, must lie in this image.
        # The constraints are: for each vector w in the orthogonal complement of local_img_mat,
        # w . (full_proj @ x) = 0 for the Selmer element x.
        # Equivalently: (w @ full_proj) . x = 0

        # Find the orthogonal complement of the column space of local_img_mat^T
        # i.e., find vectors w such that w . v = 0 for all v in local_img_mat (rows)
        # This is the null space of local_img_mat^T (or equivalently, left null space of local_img_mat)

        # Row reduce local_img_mat to find rank
        img_mat = local_img_mat.copy()
        n_rows, n_cols = img_mat.shape
        pivots = []
        col = 0
        for row_idx in range(n_rows):
            while col < n_cols:
                found = False
                for r_idx in range(row_idx, n_rows):
                    if img_mat[r_idx, col] == 1:
                        img_mat[[row_idx, r_idx]] = img_mat[[r_idx, row_idx]]
                        found = True
                        break
                if found:
                    pivots.append(col)
                    for r_idx in range(n_rows):
                        if r_idx != row_idx and img_mat[r_idx, col] == 1:
                            img_mat[r_idx] = (img_mat[r_idx] + img_mat[row_idx]) % 2
                    col += 1
                    break
                col += 1

        local_rank = len(pivots)

        # Find the orthogonal complement of the row space of local_img_mat
        # local_img_mat has shape (10, M) where M = full_proj_rows
        # Row space is a subspace of F_2^M
        # Orthogonal complement: vectors w in F_2^M with local_img_mat @ w = 0
        # This is the RIGHT null space of local_img_mat
        # Dimension = M - local_rank

        ortho_dim = n_cols - local_rank  # n_cols = full_proj_rows = M

        if ortho_dim > 0:
            # Find null space of local_img_mat (10 x M matrix)
            # i.e., vectors w in F_2^M such that local_img_mat @ w = 0
            # Use the RREF form (img_mat) which has pivots identified
            pivot_cols_set = set(pivots)
            free_cols = [c for c in range(n_cols) if c not in pivot_cols_set]

            for fc in free_cols:
                w = np.zeros(n_cols, dtype=int)
                w[fc] = 1
                # For each pivot (row_idx, pivot_col), if img_mat[row_idx, fc] == 1,
                # then we need w[pivot_col] = 1
                for row_idx, pc in enumerate(pivots):
                    if img_mat[row_idx, fc] == 1:
                        w[pc] = 1
                # Verify: local_img_mat @ w should be 0 mod 2
                # Now w is in F_2^M, and full_proj maps F_2^{total_dim} -> F_2^M
                # Constraint on x: w^T @ full_proj @ x = 0
                constraint = (w @ full_proj) % 2
                if np.any(constraint):
                    local_constraints.append(constraint.tolist())

        if verbose:
            print(f"  p={p}: local_dim={local_dim}, image_rank={local_rank}, ortho_dim={ortho_dim}")

    # Step 4: Combine all constraints
    all_constraints = norm_constraints + local_constraints
    if not all_constraints:
        return total_dim

    A = np.array(all_constraints, dtype=int) % 2

    # Row reduce to find rank of constraint matrix
    n_rows, n_cols = A.shape
    rank = 0
    for col in range(n_cols):
        found = False
        for row in range(rank, n_rows):
            if A[row, col] == 1:
                A[[rank, row]] = A[[row, rank]]
                found = True
                break
        if not found:
            continue
        for row in range(n_rows):
            if row != rank and A[row, col] == 1:
                A[row] = (A[row] + A[rank]) % 2
        rank += 1

    selmer_dim = total_dim - rank

    if verbose:
        print(f"  Total dim Q(S,2)^5 = {total_dim}")
        print(f"  Constraints: {len(norm_constraints)} norm + {len(local_constraints)} local = {len(all_constraints)}")
        print(f"  Effective rank of constraints = {rank}")
        print(f"  dim(Sel^2) = {total_dim} - {rank} = {selmer_dim}")

    return selmer_dim


def main():
    print("=" * 70)
    print("FULL 2-SELMER GROUP COMPUTATION")
    print("=" * 70)
    print()

    # Detailed analysis for small r
    print("--- Detailed analysis ---")
    for r in [2, 3, 4, 5, 6, 7, 10]:
        dim = compute_fake_selmer(r, verbose=True)
        status = "OK" if dim == 4 else "***UNEXPECTED***"
        print(f"  => dim(Sel^2) = {dim}  {status}")
        print()

    # Systematic check
    print("=" * 70)
    print("SYSTEMATIC CHECK: r = 2..100")
    print("=" * 70)

    all_ok = True
    failures = []
    for r in range(2, 101):
        dim = compute_fake_selmer(r)
        if dim != 4:
            print(f"r = {r:3d}: dim(Sel^2) = {dim}  ***")
            all_ok = False
            failures.append((r, dim))
        elif r <= 20 or r % 25 == 0:
            print(f"r = {r:3d}: dim(Sel^2) = {dim}")

    print()
    if all_ok:
        print("*** ALL r=2..100: dim(Sel^2) = 4 = dim(J[2]) ***")
        print("=> rank(J(A_r)/Q) = 0 for all r = 2..100")
    else:
        print(f"Failures: {failures}")


if __name__ == "__main__":
    main()
